version: "3.9"

services:
  backend:
    build: ./backend
    container_name: my_backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
